# This file stores the flash_commands for each mcus
# Previous version KCONFIG_CONFIG was needed now it is automaticly added when make flash is called
# version : 0.1
# tested/supported flash methods :
#  - make flash
#  - sdcard_flash
#  - flashtool.py
#  - mount/cp/umount (for rp2040)
 
[rpi]
klipper_section: mcu rpi
action_command: make flash

[mcu]
klipper_section: mcu
flash_command: ./scripts/flash-sdcard.sh /dev/ttyACM0 fysetc-spider-v1

[ebb36gen2]
klipper_section: mcu toolhead
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u <canbus_uuid>
